ETickets5.0/Controllers/ActorsController.cs
using ETickets5._0.Data;
using ETickets5._0.Data.Services;
using ETickets5._0.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace ETickets5._0.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
            _service = service;

        }

        public async Task<IActionResult> Index()
        {

            var data = await _service.getallasync();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.Addasync(actor);
           return RedirectToAction(nameof(Index));    


        }
        public async Task<IActionResult>Details (int id)
        {
            var actorDetail = await _service.GetByIdasync(id);
            if (actorDetail == null) 
            {
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(actorDetail);
            }

        }
        public async Task< IActionResult> Edit(int id)
        {
            var actorDetail = await _service.GetByIdasync(id);
            if (actorDetail == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(actorDetail);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind(" Id,FullName, ProfilePictureURL, Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id,actor);
            return RedirectToAction(nameof(Index));


        }
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetail = await _service.GetByIdasync(id);
            if (actorDetail == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(actorDetail);
            }

        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id) 
        {
            var actorDetail = await _service.GetByIdasync(id);
            if (actorDetail == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            await _service.Deleteasync(id);
           
            return RedirectToAction(nameof(Index));


        }



    }
}

ETickets5.0/Controllers/CinimasController.cs
using ETickets5._0.Data;
using ETickets5._0.Data.Services;
using ETickets5._0.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ETickets5._0.Controllers
{
    public class CinimasController : Controller
    {
        private readonly ICinemaService _service;
        public CinimasController(ICinemaService service)
        {
            _service=service;

        }
        public async Task<IActionResult> Index()

        {
            var allCinimas = await _service.getallasync();
            return View(allCinimas);
        }
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo, Name, Description")]  Cinima cinimas)
        {
            if (!ModelState.IsValid)
            {
                return View(cinimas);
            }
            await _service.Addasync(cinimas);
            return RedirectToAction(nameof(Index));


        }
       
        public async Task<IActionResult> Details(int id)
        {
            var cinimas = await _service.GetByIdasync(id);
            if (cinimas == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(cinimas);
            }
        }
        public async Task<IActionResult> Edit(int id)
        {
            var cinimas = await _service.GetByIdasync(id);
            if (cinimas == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(cinimas);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind(" Id,Logo, Name, Description")] Cinima cinima)
        {
            if (!ModelState.IsValid)
            {
                return View(cinima);
            }
            await _service.UpdateAsync(id, cinima);
            return RedirectToAction(nameof(Index));


        }
        public async Task<IActionResult> Delete(int id)
        {
            var cinima = await _service.GetByIdasync(id);
            if (cinima == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(cinima);
            }

        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinima = await _service.GetByIdasync(id);
            if (cinima == null)
            {
               
                return RedirectToAction("Error404", "Error");
            }
            await _service.Deleteasync(id);

            return RedirectToAction(nameof(Index));


        }
    }
}

ETickets5.0/Controllers/MoviesController.cs
using ETickets5._0.Data;
using ETickets5._0.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using ETickets5._0.Models;


namespace ETickets5._0.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _service;
        public MoviesController(IMovieService service)
        {

            _service = service;
        }
        public async Task<IActionResult> Index()

        {
            var allmovies = await _service.getallasync(n => n.Cinima);
            return View(allmovies);
        }
        public async Task<IActionResult> Filter(string searchString)

        {
            var allmovies = await _service.getallasync(n => n.Cinima);
           if (!string.IsNullOrEmpty(searchString))
            {
                var FilteredResult= allmovies.Where(n => n.Name.Contains(searchString)|| n.Description.Contains(searchString)).ToList();
                return View("Index", FilteredResult);
            }

           return View("Index",allmovies);

        }

        public async Task<IActionResult> Details(int id)
        {
            var moviedetails = await _service.getmovieById(id);
            if (moviedetails==null)
           
            {
                return RedirectToAction("Error404", "Error");
            }
            
            
            
            return View(moviedetails);  
           
        }
        public async Task<IActionResult> Create()
        {
            var moviedropdownlist = await _service.GetNEWmoviedropdlistMValue();
            ViewBag.CinemaId = new SelectList(moviedropdownlist.cinima, "Id", "Name");
            ViewBag.ProducerId = new SelectList(moviedropdownlist.producers, "Id", "FullName");
            ViewBag.ActorIds = new SelectList(moviedropdownlist.actors, "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {

            if (!ModelState.IsValid)
            {
                var moviedropdownlist = await _service.GetNEWmoviedropdlistMValue();
                ViewBag.CinemaId = new SelectList(moviedropdownlist.cinima, "Id", "Name");
                ViewBag.ProducerId = new SelectList(moviedropdownlist.producers, "Id", "FullName");
                ViewBag.ActorIds = new SelectList(moviedropdownlist.actors, "Id", "FullName");

                return View(movie);
            }
            else
            {
                await _service.Addnewmovieasync(movie);
                return RedirectToAction(nameof(Index));
            }

        }

        public async Task<IActionResult> Edit(int id)
        {
            var moviedetails=await _service.getmovieById(id);
            if (moviedetails == null)
            {
                return RedirectToAction("Error404", "Error");
            }


            var response = new NewMovieVM()
            {
                Id = moviedetails.Id,
                Name = moviedetails.Name,
                Description = moviedetails.Description,
                Price = moviedetails.Price,
                ImageURL = moviedetails.ImageURL,
                MovieCatagory = moviedetails.MovieCatagory,
                CinimaId = moviedetails.CinimaId,
                producerId = moviedetails.ProducerId,
                StartDate=moviedetails.StartDate,
                EndDate=moviedetails.EndDate,
                ActorsIds = moviedetails.Actor_Movies.Select(n => n.ActotId).ToList(),
            };


            var moviedropdownlist = await _service.GetNEWmoviedropdlistMValue();
            ViewBag.CinemaId = new SelectList(moviedropdownlist.cinima, "Id", "Name");
            ViewBag.ProducerId = new SelectList(moviedropdownlist.producers, "Id", "FullName");
            ViewBag.ActorIds = new SelectList(moviedropdownlist.actors, "Id", "FullName");
            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,NewMovieVM movie)
        {
            if (id != movie.Id)
            {
                return RedirectToAction("Error404", "Error");
            }


            if (!ModelState.IsValid)
            {
                var moviedropdownlist = await _service.GetNEWmoviedropdlistMValue();
                ViewBag.CinemaId = new SelectList(moviedropdownlist.cinima, "Id", "Name");
                ViewBag.ProducerId = new SelectList(moviedropdownlist.producers, "Id", "FullName");
                ViewBag.ActorIds = new SelectList(moviedropdownlist.actors, "Id", "FullName");

                return View(movie);
            }
            else
            {
                await _service.UpdateMovieAsync(movie);
                return RedirectToAction(nameof(Index));
            }

        }





    }
}
  


            

  

ETickets5.0/Controllers/OrdersController.cs
using ETickets5._0.Data.Cart;
using ETickets5._0.Data.Services;
using ETickets5._0.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ETickets5._0.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
       
        public OrdersController(IMovieService movieService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _movieService = movieService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }


        public async Task<IActionResult>Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userrole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userrole);
            return View(orders);

        }
        public IActionResult ShoppingCart()
        {
            var items=_shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                shoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item=await _movieService.getmovieById(id);
            if (item !=null)
            {
                _shoppingCart.AddItemToCart(item);

            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _movieService.getmovieById(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);

            }
            return RedirectToAction(nameof(ShoppingCart));
        }



        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAdress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAdress);
            await _shoppingCart.ClearShoppingCart();
            return View("CompleteOrder");

        }
    }
}

ETickets5.0/Controllers/ProducersController.cs
using ETickets5._0.Data;
using ETickets5._0.Data.Services;
using ETickets5._0.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ETickets5._0.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;

        }
        public async Task<IActionResult> Index()

        {
            var allProducers = await _service.getallasync();
            return View(allProducers);
        }
        public async Task<IActionResult> Details(int id)
        {
            var producerDetail = await _service.GetByIdasync(id);
            if (producerDetail == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(producerDetail);
            }
        }
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Bio")]  Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            await _service.Addasync(producer);
            return RedirectToAction(nameof(Index));


        }
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetail = await _service.GetByIdasync(id);
            if (producerDetail == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(producerDetail);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind(" Id,FullName, ProfilePictureURL, Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            await _service.UpdateAsync(id, producer);
            return RedirectToAction(nameof(Index));


        }
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetail = await _service.GetByIdasync(id);
            if (producerDetail == null)
            {
                
                return RedirectToAction("Error404", "Error");
            }
            else
            {
                return View(producerDetail);
            }

        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetail = await _service.GetByIdasync(id);
            if (producerDetail == null)
            {
                return RedirectToAction("Error404", "Error");
            }
            await _service.Deleteasync(id);

            return RedirectToAction(nameof(Index));


        }

    }
}

ETickets5.0/Views/Movies/Create.cshtml
@using ETickets5._0.Data.Enums
@model NewMovieVM
 
 


<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinimaId" class="control-label"></label>
                                <select asp-for="CinimaId" class="form-control" asp-items="ViewBag.CinemaId"></select>
                                <span asp-validation-for="CinimaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCatagory" class="control-label"></label>
                                <select asp-for="MovieCatagory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCatagory>()"></select>
                                <span asp-validation-for="MovieCatagory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="producerId" class="control-label"></label>
                                <select asp-for="producerId" class="form-control" asp-items="ViewBag.ProducerId"></select>
                                <span asp-validation-for="producerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorsIds" class="control-label"></label>
                                <select asp-for="ActorsIds" class="form-control"  asp-items="ViewBag.ActorIds" multiple></select>
                                <span asp-validation-for="ActorsIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{ 
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

ETickets5.0/Views/Movies/Details.cshtml
@model Movie

@{
    ViewData["Title"] = " Movies Details";
}

<div class="row">
   
        <div class="col-md-8 offset-2">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @Model.Name
                                    
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">@Model.Description</p>
                            <p class="card-text"><b>Cinema: </b>
                            <a asp-controller="Cinimas" asp-action="Details" asp-route-id="@Model.CinimaId" > 
                                @Model.Cinima.Name
                            </a></p>
                                 <p class="card-text"><b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId" > 
                                @Model.Producer.FullName
                            </a></p>
                            <p class="card-text"><b>Category: </b>@Model.MovieCatagory</p>
                            <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd/MM/yyyy")</p>
                            <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd/MM/yyyy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > Model.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                            <p class="card-text">
                                <b> Actors :</b>
                                <hr />
                                <div class="row">
                                    @foreach (var actor in Model.Actor_Movies)
                                   {
                                       <div class="column text-center">
                                           <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width:150px"
                                           />
                                           <br/>
                                           <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActotId">  @actor.Actor.FullName</a>
                                           </div>
                                   }


                                </div>


                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Index" >
                                   back to list
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > Model.EndDate) ? "disabled" : "")" 
                                   asp-controller="Orders" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                                <br/>
                                <br/>
                                
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
</div>

ETickets5.0/Views/Movies/Index.cshtml
@model IEnumerable<Movie>


@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {<a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id" asp-controller="Movies"><i class="bi bi-pencil-square"></i></a>
                                    }

                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinima.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCatagory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd/MM/yyyy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd/MM/yyyy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")" 
                                   asp-controller="Orders" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@item.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                                <br/>
                                <br/>
                                 
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@await Html.PartialAsync("CreateItem", "Movies") 